/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "src/**/*.{html,js,ts,jsx,tsx}",
    "./node_modules/flowbite-react/**/*.js",
  ],
  theme: {
    fontFamily: {
      edenred: ["Edenred"],
      ubuntu: ["Ubuntu"],
    },
    colors: {
      black: "#000000",
      white: "#FFFFFF",
      "pedagio-blue": "#0D8AFF",
      "pedagio-blue-hover": "#0A76DB",
      "pedagio-blue-top-header": "#00859b",
      "pedagio-light-blue": "#B0EFFF",
      "pedagio-dark-blue": "#010050",
      "pedagio-secondary-blue": "#E7F3FF",
      "pedagio-grey": "#6D7787",
      "pedagio-light-grey": "#D5D8DD",
      "pedagio-red": "#F72717",
      "abastecimento-violet": "#711CFF",
      "abastecimento-violet-hover": "#4100b3",
      "abastecimento-light-violet": "#C8C3FF",
      "abastecimento-light-grey": "#D5D8DD",
      "abastecimento-olive": "#739A00",
      "abastecimento-light-olive": "#DCF691",
      "abastecimento-olive-background": "#F1F5E6",
      "abastecimento-olive-light-background": "#FAFEEF",
      "abastecimento-blue-light-background": "#F0FEFA",
      "abastecimento-grey": "#6D7787",
      "abastecimento-red": "#F72717",
      "tlog-blue-light-background": "#F2FAF9",
      "tlog-olive-light-background": "#F8FAF2",
      "tlog-olive": "#739A00",
      "tlog-olive-bg": "#F1F5E6",
      "tlog-green": "#00A184",
      "tlog-green-bg": "#F2FAF9",
      "tlog-light-olive": "#DCF691",
      "tlog-grey": "#6D7787",
    },
  },
  plugins: [require("flowbite/plugin"), require("tailwind-scrollbar-hide")],
};
